### ISSUE TITLE
Aiming at the problem of not being able to download on the Internet, select the path

### ISSUE THREAD

**Issue by zsyggg** [Teddy-XiongGZ/MedRAG#11]
Thank you for your work, but because my lab server is not connected to the Internet, I choose to manually download the pubmed data set and the three models of MedCPT and store them in the figure. But when I execute the call command, I fill in the path and report that the Assert name is wrong. So I filled in names anyway, and it kept telling me to download the Article-Encoder from the Internet? Is my LLM choice PMC_LLAMA_7B feasible for the toolkit?
![J2WBN 45WN`YW09@R4Z(U N](https://github.com/Teddy-XiongGZ/MedRAG/assets/136660384/6902def8-7f09-4c67-9d9b-c9385778c30f)
![OVM{7E4$B@21P{88K@(7EF](https://github.com/Teddy-XiongGZ/MedRAG/assets/136660384/4e974090-6334-47d1-a9d4-0b2733d047b9)

**Comment by gzxiong** [comment]
To use local models instead of downloading them from the Internet, please save your model in the default cache directory for SentenceTransformer models, which is normally at `~/.cache/torch/sentence_transformers`. The folder names should look like `ncbi_MedCPT-Article-Encoder` or `ncbi_MedCPT-Query-Encoder`.
