### ISSUE TITLE
Request the MedCorp corpus data

### ISSUE THREAD

**Issue by PeterGriffinJin** [Teddy-XiongGZ/MedRAG#12]
Hi there,

Thank you so much for your nice work!

Can I request if you could share the MedCorp directly with us?

I find your corpus files in HF dataset hub: https://huggingface.co/datasets/MedRAG. However, it seems that some of them are empty and the size of some of them are not aligned with those used in your paper.

Best,
Bowen

**Comment by gzxiong** [comment]
Hi Bowen,

Thanks for your interest in our work! The MedCorp corpus is basically a combination of Textbooks, StatPearls, PubMed, and Wikipedia. You can directly obtain it by downloading the four corpora from [HF](https://huggingface.co/MedRAG).

Due to the [privacy policy](https://www.statpearls.com/home/privacypolicy/) of StatPearls, we did not upload its chunks to HF. However, we provide a piece of [code](https://github.com/Teddy-XiongGZ/MedRAG/blob/main/src/utils.py#L121) to automatically download the raw data of StatPearls and process it as chunks. Also, be careful that the chunks on HF should be downloaded with "git clone" instead of the usual "dataset" Python package ([code](https://github.com/Teddy-XiongGZ/MedRAG/blob/main/src/utils.py#L119)). 

Feel free to ask if you have further questions.

Best,
Guangzhi

**Comment by ddofer** [comment]
The "Textbooks" dataset seems to fail/be empty.

`medrag = MedRAG(llm_name=LL_NAME, rag=True, retriever_name="MedCPT", corpus_name="Textbooks")`
-> ...

```

File ~/anaconda3/envs/Medrag/lib/python3.11/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by gzxiong** [comment]
Did you install `git-lfs` on your machine when downloading the chunks? This software is needed to download them correctly.

**Comment by ddofer** [comment]
Issue solved - I had installed git-lfs using pip, rather than with brew. The latter is needed in order to download. (And the code doesn't warn about it/the data being missing).
