### ISSUE TITLE
 Seeking guidance on setting RRF parameters

### ISSUE THREAD

**Issue by Jack-ZC8** [Teddy-XiongGZ/MedRAG#16]
https://github.com/Teddy-XiongGZ/MedRAG/blob/5b8e8572079873683c15d769aa4f20f5e0c6d5f7/src/utils.py#L208

Hello, thanks for your wonderful codes. I have a simple questions.
How should I determine the appropriate value for the k_ parameter for the separate retrievers in the RRF method?

**Comment by gzxiong** [comment]
The **k_** value will be dynamically determined by the **k** value you enter. Since RRF combines the ranking information from multiple retrievers, we let each retriever return more than k snippets to obtain a more comprehensive knowledge of the ranking fusion. The default value of k is 32 in our system.

**Comment by Jack-ZC8** [comment]
Thanks for your reply! I'd also like to ask if there's any rationale for the doubling here.

**Comment by gzxiong** [comment]
Not yet. We tried the double size because it looked neat. You can certainly try other multiples.

**Comment by Jack-ZC8** [comment]
OK, thanks very much!
